### ISSUE TITLE
While executing rake chores:tarantula:test,following errors throws

### ISSUE THREAD

**Issue by railsfactory-dhibika** [relevance/tarantula#27]
```
/home/dhibika/ruby/1.8/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:240:in `require': no such file to load -- action_controller/integration (LoadError)
    from /home/dhibika/ruby/1.8/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:240:in `require'
    from /home/dhibika/ruby/1.8/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /home/dhibika/ruby/1.8/gems/activesupport-3.1.1/lib/active_support/dependencies.rb:240:in `require'
    from /home/dhibika/projects/rails3/chorepay/config/environment.rb:6
    from /home/dhibika/projects/rails3/chorepay/test/tarantula/../test_helper.rb:2:in `require'
    from /home/dhibika/projects/rails3/chorepay/test/tarantula/../test_helper.rb:2
    from /home/dhibika/projects/rails3/chorepay/test/tarantula/tarantula_test.rb:1:in `require'
    from /home/dhibika/projects/rails3/chorepay/test/tarantula/tarantula_test.rb:1
    from /home/dhibika/ruby/1.8/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:10:in `require'
    from /home/dhibika/ruby/1.8/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:10
    from /home/dhibika/ruby/1.8/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:9:in `each'
    from /home/dhibika/ruby/1.8/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:9
    from /home/dhibika/ruby/1.8/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:4:in `select'
    from /home/dhibika/ruby/1.8/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:4
rake aborted!
Command failed with status (1): [/usr/bin/ruby1.8 -I"lib:test" -I"/home/dhi...]

Tasks: TOP => tarantula_test
(See full trace by running task with --trace)
```

**Comment by rsanheim** [comment]
I don't know what `rake chores` is -- I'm guessing you are using a 3rd party plugin that is calling tarantula?

Can you provide more details?

**Comment by railsfactory-dhibika** [comment]
Thanks for your reply

I am using relevance-tarantula-0.3.3 plugin

I referred this link http://www.icoretech.org/2009/10/rails-vs-tarantula/
